import Foundation

/// An error that occurs while generating a response.
/// 
/// **Apple Foundation Models Documentation:**
/// An error that occurs while generating a response.
/// 
/// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror
/// 
/// **Apple Official API:** `enum GenerationError`
/// - iOS 26.0+, iPadOS 26.0+, macOS 26.0+, visionOS 26.0+
/// - Beta Software: Contains preliminary API information
/// 
/// **Conformances:**
/// - Error
/// - LocalizedError
/// - Sendable
/// - SendableMetatype
/// 
/// **Note:** Defined as top-level for Swift compatibility, but conceptually nested under LanguageModelSession
public enum GenerationError: Error, LocalizedError, Sendable, SendableMetatype {
        
        /// An error that indicates the assets required for the session are unavailable.
        /// 
        /// **Apple Foundation Models Documentation:**
        /// An error that indicates the assets required for the session are unavailable.
        /// 
        /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/assetsunavailable(_:)
        /// 
        /// **Apple Official API:** `case assetsUnavailable(LanguageModelSession.GenerationError.Context)`
        case assetsUnavailable(Context)
        
        /// An error that happens if you attempt to make a session respond to a second prompt while it's still responding to the first one.
        /// 
        /// **Apple Foundation Models Documentation:**
        /// An error that happens if you attempt to make a session respond to a second prompt while it's still responding to the first one.
        /// 
        /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/concurrentrequests(_:)
        /// 
        /// **Apple Official API:** `case concurrentRequests(LanguageModelSession.GenerationError.Context)`
        case concurrentRequests(Context)
        
        /// An error that indicates the session failed to deserialize a valid generable type from model output.
        /// 
        /// **Apple Foundation Models Documentation:**
        /// An error that indicates the session failed to deserialize a valid generable type from model output.
        /// 
        /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/decodingfailure(_:)
        /// 
        /// **Apple Official API:** `case decodingFailure(LanguageModelSession.GenerationError.Context)`
        case decodingFailure(Context)
        
        /// An error that signals the session reached its context window size limit.
        /// 
        /// **Apple Foundation Models Documentation:**
        /// An error that signals the session reached its context window size limit.
        /// 
        /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/exceededcontextwindowsize(_:)
        /// 
        /// **Apple Official API:** `case exceededContextWindowSize(LanguageModelSession.GenerationError.Context)`
        case exceededContextWindowSize(Context)
        
        /// An error that indicates the system's safety guardrails are triggered by content in a prompt or the response generated by the model.
        /// 
        /// **Apple Foundation Models Documentation:**
        /// An error that indicates the system's safety guardrails are triggered by content in a prompt 
        /// or the response generated by the model.
        /// 
        /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/guardrailviolation(_:)
        /// 
        /// **Apple Official API:** `case guardrailViolation(LanguageModelSession.GenerationError.Context)`
        case guardrailViolation(Context)
        
        /// An error that indicates your session has been rate limited.
        /// 
        /// **Apple Foundation Models Documentation:**
        /// An error that indicates your session has been rate limited.
        /// 
        /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/ratelimited(_:)
        /// 
        /// **Apple Official API:** `case rateLimited(LanguageModelSession.GenerationError.Context)`
        case rateLimited(Context)
        
        /// An error that indicates a generation guide with an unsupported pattern was used.
        /// 
        /// **Apple Foundation Models Documentation:**
        /// An error that indicates a generation guide with an unsupported pattern was used.
        /// 
        /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/unsupportedguide(_:)
        /// 
        /// **Apple Official API:** `case unsupportedGuide(LanguageModelSession.GenerationError.Context)`
        case unsupportedGuide(Context)
        
        /// An error that indicates an error that occurs if the model is prompted to respond in a language that it does not support.
        /// 
        /// **Apple Foundation Models Documentation:**
        /// An error that indicates an error that occurs if the model is prompted to respond in a language that it does not support.
        /// 
        /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/unsupportedlanguageorlocale(_:)
        /// 
        /// **Apple Official API:** `case unsupportedLanguageOrLocale(LanguageModelSession.GenerationError.Context)`
        case unsupportedLanguageOrLocale(Context)
    
    /// The context in which the error occurred.
    /// 
    /// **Apple Foundation Models Documentation:**
    /// The context in which the error occurred.
    /// 
    /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/context
    /// 
    /// **Apple Official API:** `struct Context`
    /// 
    /// **Conformances:**
    /// - Sendable
    /// - SendableMetatype
    public struct Context: Sendable, SendableMetatype {
        /// A debug description to help developers diagnose issues during development.
        /// 
        /// **Apple Foundation Models Documentation:**
        /// A debug description to help developers diagnose issues during development.
        /// 
        /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/context/debugdescription
        /// 
        /// **Apple Official API:** `let debugDescription: String`
        public let debugDescription: String
        
        /// Creates a context.
        /// 
        /// **Apple Foundation Models Documentation:**
        /// Creates a context.
        /// 
        /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/context/init(debugdescription:)
        /// 
        /// **Apple Official API:** `init(debugDescription: String)`
        /// 
        /// - Parameter debugDescription: A debug description to help developers diagnose issues
        public init(debugDescription: String) {
            self.debugDescription = debugDescription
        }
    }
}

// MARK: - Error Description

extension GenerationError {
    
    /// A string representation of the error description.
    /// 
    /// **Apple Foundation Models Documentation:**
    /// A string representation of the error description.
    /// 
    /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/errordescription
    /// 
    /// **Apple Official API:** `var errorDescription: String`
    public var errorDescription: String? {
        switch self {
        case .assetsUnavailable(let context):
            return "Assets unavailable: \(context.debugDescription)"
            
        case .concurrentRequests(let context):
            return "Concurrent requests: \(context.debugDescription)"
            
        case .decodingFailure(let context):
            return "Decoding failure: \(context.debugDescription)"
            
        case .exceededContextWindowSize(let context):
            return "Context window size exceeded: \(context.debugDescription)"
            
        case .guardrailViolation(let context):
            return "Guardrail violation: \(context.debugDescription)"
            
        case .rateLimited(let context):
            return "Rate limited: \(context.debugDescription)"
            
        case .unsupportedGuide(let context):
            return "Unsupported guide: \(context.debugDescription)"
            
        case .unsupportedLanguageOrLocale(let context):
            return "Unsupported language or locale: \(context.debugDescription)"
        }
    }
    
    /// A string representation of the failure reason.
    /// 
    /// **Apple Foundation Models Documentation:**
    /// A string representation of the failure reason.
    /// 
    /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/failurereason
    /// 
    /// **Apple Official API:** `var failureReason: String?`
    public var failureReason: String? {
        switch self {
        case .assetsUnavailable:
            return "The assets required for the session are unavailable."
            
        case .concurrentRequests:
            return "You attempted to make a session respond to a second prompt while it's still responding to the first one."
            
        case .decodingFailure:
            return "The session failed to deserialize a valid generable type from model output."
            
        case .exceededContextWindowSize:
            return "The session reached its context window size limit."
            
        case .guardrailViolation:
            return "The system's safety guardrails were triggered by content in a prompt or the response generated by the model."
            
        case .rateLimited:
            return "Your session has been rate limited."
            
        case .unsupportedGuide:
            return "A generation guide with an unsupported pattern was used."
            
        case .unsupportedLanguageOrLocale:
            return "The model was prompted to respond in a language that it does not support."
        }
    }
    
    /// A string representation of the recovery suggestion.
    /// 
    /// **Apple Foundation Models Documentation:**
    /// A string representation of the recovery suggestion.
    /// 
    /// **Source:** https://developer.apple.com/documentation/foundationmodels/languagemodelsession/generationerror/recoverysuggestion
    /// 
    /// **Apple Official API:** `var recoverySuggestion: String?`
    public var recoverySuggestion: String? {
        switch self {
        case .assetsUnavailable:
            return "Check that the required model assets are available and try again."
            
        case .concurrentRequests:
            return "Wait for the current response to complete before making another request."
            
        case .decodingFailure:
            return "Check your generable type definition and try again."
            
        case .exceededContextWindowSize:
            return "Try reducing the length of your prompt or conversation history."
            
        case .guardrailViolation:
            return "Please modify your prompt to avoid sensitive or inappropriate content."
            
        case .rateLimited:
            return "Wait a moment and try again, or reduce the frequency of your requests."
            
        case .unsupportedGuide:
            return "Use a supported generation guide pattern and try again."
            
        case .unsupportedLanguageOrLocale:
            return "Try using a supported language or check model capabilities."
        }
    }
}

// MARK: - Error Codes

extension GenerationError {
    
    /// Error codes for different types of generation errors
    /// ✅ APPLE SPEC: Error codes for programmatic handling
    public var errorCode: Int {
        switch self {
        case .assetsUnavailable:
            return 1001
        case .concurrentRequests:
            return 1002
        case .decodingFailure:
            return 1003
        case .exceededContextWindowSize:
            return 1004
        case .guardrailViolation:
            return 1005
        case .rateLimited:
            return 1006
        case .unsupportedGuide:
            return 1007
        case .unsupportedLanguageOrLocale:
            return 1008
        }
    }
}

// MARK: - Convenience Methods

extension GenerationError {
    
    /// Check if the error is recoverable
    /// ✅ APPLE SPEC: Utility method for error handling
    public var isRecoverable: Bool {
        switch self {
        case .assetsUnavailable, .concurrentRequests, .decodingFailure:
            return true
        case .exceededContextWindowSize, .guardrailViolation, .rateLimited:
            return true
        case .unsupportedGuide, .unsupportedLanguageOrLocale:
            return true
        }
    }
    
    /// Check if the error is due to user input
    /// ✅ APPLE SPEC: Utility method for error classification
    public var isUserInputError: Bool {
        switch self {
        case .decodingFailure, .exceededContextWindowSize, .guardrailViolation:
            return true
        case .unsupportedGuide, .unsupportedLanguageOrLocale:
            return true
        case .assetsUnavailable, .concurrentRequests, .rateLimited:
            return false
        }
    }
}