// ProtocolConformances.swift
// OpenFoundationModels
//
// ✅ CONFIRMED: Standard type conformances for Apple Foundation Models API

import Foundation
import OpenFoundationModelsCore

// MARK: - Standard Type Conformances

/// String conformance to Generable
/// 
/// **Apple Foundation Models Documentation:**
/// String is a fundamental type that can be generated by language models.
/// This conformance allows String to be used directly in generation methods.
/// 
/// **Source:** https://developer.apple.com/documentation/foundationmodels/generable
extension String: InstructionsRepresentable, PromptRepresentable {
    /// Convert to instructions representation
    public var instructionsRepresentation: Instructions {
        return Instructions(self)
    }
    
    /// Convert to prompt representation
    public var promptRepresentation: Prompt {
        return Prompt(self)
    }
}

extension String: Generable {
    /// Partially generated string content
    /// 
    /// **Apple Foundation Models Documentation:**
    /// Represents string content that is being generated incrementally.
    public typealias PartiallyGenerated = GeneratedContent
    
    /// The generation schema for String content
    /// 
    /// **Apple Foundation Models Documentation:**
    /// String content uses a simple text schema for generation.
    public static var generationSchema: GenerationSchema {
        return GenerationSchema(
            type: "string",
            description: "Text content",
            anyOf: []
        )
    }
    
    /// Create String from generated content
    /// 
    /// **Apple Foundation Models Documentation:**
    /// Extracts string content from generated output.
    /// ✅ CONFIRMED: Required by ConvertibleFromGeneratedContent
    public init(_ content: GeneratedContent) throws {
        self = content.text
    }
    
    /// Convert String to generated content
    /// 
    /// **Apple Foundation Models Documentation:**
    /// Converts string to generated content format.
    /// ✅ CONFIRMED: Required by ConvertibleToGeneratedContent
    public var generatedContent: GeneratedContent {
        return GeneratedContent(self)
    }
    
    /// Convert to partially generated representation
    /// 
    /// **Apple Foundation Models Documentation:**
    /// Converts string to partially generated content for streaming.
    public func toPartiallyGenerated() -> PartiallyGenerated {
        return GeneratedContent(self)
    }
    
    /// Convert to partially generated representation (instance method)
    /// 
    /// **Apple Foundation Models Documentation:**
    /// Instance method for converting to partially generated content.
    public func asPartiallyGenerated() -> PartiallyGenerated {
        return GeneratedContent(self)
    }
}

// GeneratedContent conformances are already defined in OpenFoundationModelsCore

extension GeneratedContent: Generable {
    /// Partially generated content representation
    /// 
    /// **Apple Foundation Models Documentation:**
    /// GeneratedContent can represent partially generated content.
    public typealias PartiallyGenerated = GeneratedContent
    
    /// The generation schema for GeneratedContent
    /// 
    /// **Apple Foundation Models Documentation:**
    /// GeneratedContent uses a flexible schema that can represent various content types.
    public static var generationSchema: GenerationSchema {
        return GenerationSchema(
            type: "object",
            description: "Generated content with flexible structure"
        )
    }
    
    // ConvertibleFromGeneratedContent conformance is already in GeneratedContent.swift
    // ConvertibleToGeneratedContent conformance: generatedContent property is already in GeneratedContent.swift
    
    /// Convert to partially generated representation (identity function)
    /// 
    /// **Apple Foundation Models Documentation:**
    /// Identity transformation for GeneratedContent.
    public func toPartiallyGenerated() -> PartiallyGenerated {
        return self
    }
    
    /// Convert to partially generated representation (instance method)
    /// 
    /// **Apple Foundation Models Documentation:**
    /// Instance method for converting to partially generated content.
    public func asPartiallyGenerated() -> PartiallyGenerated {
        return self
    }
}